#!/usr/bin/env python3
"""Generate ECDSA P-256 OTA signing keys (and optional AES-256 key).

Writes:
  keys/ota_private.pem   — keep secret; used by sign_firmware.py
  keys/ota_public.pem    — public key (also embedded in firmware)
  keys/ota_public.h      — drop-in snippet for src/ota_signing_config.h
  keys/ota_aes.key       — optional 32-byte AES key (hex), if --aes

Usage:
  python scripts/generate_ota_keys.py
  python scripts/generate_ota_keys.py --aes
  python scripts/generate_ota_keys.py --out-dir path/to/keys
"""

from __future__ import annotations

import argparse
import os
import sys


def _require_cryptography():
    try:
        from cryptography.hazmat.primitives.asymmetric import ec
        from cryptography.hazmat.primitives import serialization
        from cryptography.hazmat.backends import default_backend
        return ec, serialization, default_backend
    except ImportError:
        print(
            "Missing dependency: cryptography\n"
            "  pip install cryptography",
            file=sys.stderr,
        )
        sys.exit(1)


def _c_array(name: str, data: bytes, per_line: int = 8) -> str:
    lines = [f"static const uint8_t {name}[{len(data)}] = {{"]
    for i in range(0, len(data), per_line):
        chunk = data[i : i + per_line]
        hexes = ", ".join(f"0x{b:02x}" for b in chunk)
        comma = "," if i + per_line < len(data) else ""
        lines.append(f"    {hexes}{comma}")
    lines.append("};")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate OTA signing keys")
    parser.add_argument(
        "--out-dir",
        default="keys",
        help="Output directory (default: keys/)",
    )
    parser.add_argument(
        "--aes",
        action="store_true",
        help="Also generate a random AES-256 key for encrypted packages",
    )
    args = parser.parse_args()

    ec, serialization, default_backend = _require_cryptography()

    os.makedirs(args.out_dir, exist_ok=True)

    private_key = ec.generate_private_key(ec.SECP256R1(), default_backend())
    public_key = private_key.public_key()

    priv_pem = private_key.private_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PrivateFormat.PKCS8,
        encryption_algorithm=serialization.NoEncryption(),
    )
    pub_pem = public_key.public_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PublicFormat.SubjectPublicKeyInfo,
    )

    numbers = public_key.public_numbers()
    pub_x = numbers.x.to_bytes(32, "big")
    pub_y = numbers.y.to_bytes(32, "big")

    priv_path = os.path.join(args.out_dir, "ota_private.pem")
    pub_path = os.path.join(args.out_dir, "ota_public.pem")
    header_path = os.path.join(args.out_dir, "ota_public.h")

    with open(priv_path, "wb") as f:
        f.write(priv_pem)
    with open(pub_path, "wb") as f:
        f.write(pub_pem)

    aes_block = ""
    if args.aes:
        aes_key = os.urandom(32)
        aes_path = os.path.join(args.out_dir, "ota_aes.key")
        with open(aes_path, "w", encoding="utf-8") as f:
            f.write(aes_key.hex() + "\n")
        aes_block = "\n" + _c_array("OTA_AES_KEY", aes_key) + "\n"
        print(f"Wrote {aes_path}")

    header = f"""// Generated by scripts/generate_ota_keys.py
// Copy OTA_PUBLIC_KEY_X / OTA_PUBLIC_KEY_Y into src/ota_signing_config.h
// Optionally set #define OTA_SIGNATURE_ENFORCE 1
//
// NEVER commit ota_private.pem or ota_aes.key

{_c_array("OTA_PUBLIC_KEY_X", pub_x)}

{_c_array("OTA_PUBLIC_KEY_Y", pub_y)}
{aes_block}"""
    with open(header_path, "w", encoding="utf-8") as f:
        f.write(header)

    # Restrict private key permissions where the OS supports it
    try:
        os.chmod(priv_path, 0o600)
    except OSError:
        pass

    print(f"Wrote {priv_path}  (KEEP SECRET)")
    print(f"Wrote {pub_path}")
    print(f"Wrote {header_path}")
    print()
    print("Next steps:")
    print("  1. Copy public key arrays into src/ota_signing_config.h")
    print("  2. Optionally set OTA_SIGNATURE_ENFORCE to 1")
    print("  3. Flash the device once (serial) so it has the public key")
    print("  4. Sign firmware: python scripts/sign_firmware.py .pio/build/.../firmware.bin")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
